# Generated by Django 5.2 on 2025-04-14 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('type', models.CharField(choices=[('CEDIS', 'Distribution Center (CEDIS)'), ('SUCURSAL', 'Branch/Customer'), ('PROVEEDOR', 'Supplier')], default='SUCURSAL', max_length=10)),
                ('opening_time', models.TimeField(blank=True, help_text='Start of operating/delivery window', null=True)),
                ('closing_time', models.TimeField(blank=True, help_text='End of operating/delivery window', null=True)),
                ('average_service_time_mins', models.PositiveIntegerField(default=0, help_text='Average time spent at location in minutes')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('max_weight_kg', models.FloatField(help_text='Maximum weight capacity in kilograms')),
                ('max_volume_m3', models.FloatField(help_text='Maximum volume capacity in cubic meters')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PLANNER', 'Planner'), ('MANAGER', 'Logistics Manager'), ('FLEET_ADMIN', 'Fleet Administrator'), ('ADMIN', 'System Administrator')], default='PLANNER', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('make', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('vin', models.CharField(blank=True, help_text='Vehicle Identification Number', max_length=17, null=True, unique=True)),
                ('current_odometer_km', models.FloatField(default=0)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Is the vehicle available for routing?')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='api.vehicletype')),
            ],
        ),
    ]
