# Generated by Django 5.2 on 2025-04-14 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_route_task_routestop'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('interval_km', models.PositiveIntegerField(blank=True, help_text='Recommended interval in kilometers', null=True)),
                ('interval_days', models.PositiveIntegerField(blank=True, help_text='Recommended interval in days', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(blank=True, db_index=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('odometer_at_maintenance', models.FloatField(blank=True, help_text='Odometer reading when maintenance was done/scheduled', null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=15)),
                ('unavailable_start_date', models.DateField(blank=True, null=True)),
                ('unavailable_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='api.vehicle')),
                ('maintenance_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.maintenancetype')),
            ],
            options={
                'ordering': ['-scheduled_date', '-completion_date'],
            },
        ),
    ]
